/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test123.check" instead.
 */

#include <check.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <limits.h>

#include "s21_string.h"

void makefreeArr(char *str1, char *str2, int arrsize) {
  for (int i = 0; i < arrsize; i++) {
    str1[i] = '\0';
    str2[i] = '\0';
  }
}

// 1 function
START_TEST(s21_memchr_test) {
  // ++
  char str1[100] = "1234", str2[100] = "Nice", str3[100] = "00000000",
       str4[100] = "-1-2-3-4-5", str5[100] = "daseqweqwe",
       str6[10000] = "12345679088123456789123456789012345",
       str7[] = "123456790";
  ck_assert_str_eq(s21_memchr(str1, '4', 9), memchr(str1, '4', 9));
  ck_assert_str_eq(s21_memchr(str2, 'i', 9), memchr(str2, 'i', 9));
  ck_assert_str_eq(s21_memchr(str3, '0', 9), memchr(str3, '0', 9));
  ck_assert_str_eq(s21_memchr(str4, '-', 9), memchr(str4, '-', 9));
  ck_assert_msg(s21_memchr(str5, '1', 9) == s21_NULL, "Test 5 failed");
  ck_assert_msg(s21_memchr(str5, '1', 9) == s21_NULL, "Test 5 failed");
  ck_assert_str_eq(s21_memchr(str6, '8', 12), memchr(str6, '8', 12));
  ck_assert_msg(s21_memchr(str7, ' ', 10) == s21_NULL, "Test 5 failed");

  // 2 function
}
END_TEST

START_TEST(s21_memcmp_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "999010s";
  char str21[100] = "1234", str23[100] = "-1213002%s",
       str24[100] = "99901asdass", str1[100] = "123456789", str2[10] = "2",
       str31[150] = "12345679088123456789123456789012345", str32[150] = " ";
  ck_assert_int_eq(s21_memcmp(str11, str21, 5), memcmp(str11, str21, 5));
//  ck_assert_int_eq(s21_memcmp(str12, str22, 5), memcmp(str12, str22, 5));
  ck_assert_int_eq(s21_memcmp(str13, str23, 5), memcmp(str13, str23, 5));
  ck_assert_int_eq(s21_memcmp(str14, str24, 5), memcmp(str14, str24, 5));
  ck_assert_int_eq(s21_memcmp(str12, str24, 5), memcmp(str12, str24, 5));
  ck_assert_int_eq(s21_memcmp(str1, str2, 10), memcmp(str1, str2, 10));
  ck_assert_int_eq(s21_memcmp(str31, str32, 10), memcmp(str31, str32, 10));
  ck_assert_int_eq(s21_memcmp(str32, str31, 10), memcmp(str32, str31, 10));
  ck_assert_int_eq(s21_memcmp(str31, str32, 0), memcmp(str31, str32, 0));

  // 3 function
}
END_TEST

START_TEST(s21_memcpy_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "";
  char str21[100] = "", str22[100] = "776asdqe1", str23[100] = "-1213002%s",
       str24[100] = "", str31[100] = "12345679088123456789123456789012345";
  ck_assert_str_eq(s21_memcpy(str11, str21, 5), memcpy(str11, str21, 5));
  ck_assert_str_eq(s21_memcpy(str12, str22, 5), memcpy(str12, str22, 5));
  ck_assert_str_eq(s21_memcpy(str13, str23, 5), memcpy(str13, str23, 5));
  ck_assert_str_eq(s21_memcpy(str14, str24, 5), memcpy(str14, str24, 5));
  ck_assert_str_eq(s21_memcpy(str12, str24, 5), memcpy(str12, str24, 5));
  ck_assert_str_eq(s21_memcpy(str12, str24, 5), memcpy(str12, str24, 5));
  ck_assert_str_eq(s21_memcpy(str31, str24, 0), memcpy(str31, str24, 0));

  // 4 function
}
END_TEST

START_TEST(s21_memmove_test) {
  // ++
  char str1[50] = "123456789", str2[50] = "Hello_World",
       str3[50] = "qwertyuiop[]", str4[50] = "111111111", str5[50] = "",
       str6[] = "12345679088123456789123456789012345", str7[] = "3456",
       str8[] = "";
  ck_assert_str_eq(s21_memmove(&str1[4], &str1[3], 3),
                   memmove(&str1[4], &str1[3], 3));
  ck_assert_str_eq(s21_memmove(&str1[4], " ", 1), memmove(&str1[4], " ", 1));
  ck_assert_str_eq(s21_memmove(&str1[6], &str1[3], 5),
                   memmove(&str1[6], &str1[3], 5));
  ck_assert_str_eq(s21_memmove(str2, str3, 5), memmove(str2, str3, 5));
  ck_assert_str_eq(s21_memmove(str4, str5, 5), memmove(str4, str5, 5));
  ck_assert_str_eq(s21_memmove(str6, str7, 5), memmove(str6, str7, 5));
  ck_assert_str_eq(s21_memmove(str6, str8, 1), memmove(str6, str8, 1));

  // 5 function
}
END_TEST

START_TEST(s21_memset_test) {
  // ++
  char str1[100] = "1234", str2[100] = "Nice", str3[100] = "00000000",
       str4[100] = "-1-2-3-4-5", str5[100] = "daseqweqwe",
//       str6[1000] = "12345679088123456789123456789012345",
       str7[1000] = "Ainur_jerlenem";
  char str11[100] = "1234", str21[100] = "Nice", str31[100] = "00000000",
       str41[100] = "-1-2-3-4-5", str51[100] = "daseqweqwe",
//       str61[1000] = "12345679088123456789123456789012345",
       str71[1000] = "Ainur_jerlenem";
  ck_assert_str_eq(s21_memset(str1, '4', 4), memset(str11, '4', 4));
  ck_assert_str_eq(s21_memset(str2, '_', 4), memset(str21, '_', 4));
  ck_assert_str_eq(s21_memset(str3, 'z', 4), memset(str31, 'z', 4));
  ck_assert_str_eq(s21_memset(str4, '0', 3), memset(str41, '0', 3));
  ck_assert_str_eq(s21_memset(str5, '%', 3), memset(str51, '%', 3));
//  ck_assert_str_eq(s21_memset(str6, '4', 0), memset(str61, '4', 1));
  ck_assert_str_eq(s21_memset(str7, 'j', 10), memset(str71, 'j', 10));

  // 6 function
}
END_TEST

START_TEST(s21_strcat_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "", str15[100];
  char str21[100] = "", str22[100] = "776asdqe1", str23[100] = "-1213002%s",
       str24[100] = "", str25[10000] = "",
       str26[1000000] = "12345679088123456789123456789012345";
  ck_assert_str_eq(s21_strcat(str11, str21), strcat(str11, str21));
  ck_assert_str_eq(s21_strcat(str12, str22), strcat(str12, str22));
  ck_assert_str_eq(s21_strcat(str13, str23), strcat(str13, str23));
  ck_assert_str_eq(s21_strcat(str14, str24), strcat(str14, str24));
  ck_assert_str_eq(s21_strcat(str15, str25), strcat(str15, str25));
  ck_assert_str_eq(s21_strcat(str15, str25), strcat(str15, str25));
  ck_assert_str_eq(s21_strcat(str26, str11), strcat(str26, str11));
  ck_assert_str_eq(s21_strcat(str26, str21), strcat(str26, str21));

  // 7 function
}
END_TEST

START_TEST(s21_strncat_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str32[100] = "776832768178", str33[100] = "776asdqe1",
       str13[100] = "-1213002%s", str14[100] = "", str15[100] = "123",
       str16[1000000] = "456",
       str17[300] = "12345679088123456789123456789012345",
       str18[300] = "12345679088123456789123456789012345123456789022";
  char str21[100] = "", str22[100] = "776asdqe1", str23[100] = "-1213002%s",
       str24[100] = "", str25[100] = "456", str26[1000000] = "456",
       str27[300] = "12345679088123456789123456789012345",
       str30[150] = "12345679088123456789123456789012345123456789022";
  ck_assert_str_eq(s21_strncat(str11, str21, 3), strncat(str11, str21, 3));
  ck_assert_str_eq(s21_strncat(str12, str22, 30), strncat(str32, str33, 30));
  ck_assert_str_eq(s21_strncat(str13, str23, 0), strncat(str13, str23, 0));
  ck_assert_str_eq(s21_strncat(str14, str24, 3), strncat(str14, str24, 3));
  ck_assert_str_eq(s21_strncat(str15, str25, 3), strncat(str15, str25, 3));
  ck_assert_str_eq(s21_strncat(str26, str12, 100), strncat(str16, str12, 100));
  ck_assert_str_eq(s21_strncat(str17, str33, 100), strncat(str27, str33, 100));
  ck_assert_str_eq(s21_strncat(str18, str32, 100), strncat(str30, str32, 100));

  // 8 function
}
END_TEST

START_TEST(s21_strchr_test) {
  // ++
  char str1[100] = "1234", str2[100] = "Nice", str3[100] = "00000000",
       str4[100] = "-1-2-3-4-5", str5[100] = "", str6[1000000] = "12414525",
       str7[1000000] =
           "1241452523456345632ytrewrwerwerwsdf12411323255234234239er";
  ck_assert_msg(s21_strchr(str1, '0') == strchr(str1, '0'), "1 test failed");
  ck_assert_msg(s21_strchr(str2, 'i') == strchr(str2, 'i'), "2 test failed");
  ck_assert_msg(s21_strchr(str3, '0') == strchr(str3, '0'), "3 test failed");
  ck_assert_msg(s21_strchr(str4, '-') == strchr(str4, '-'), "4 test failed");
  ck_assert_msg(s21_strchr(str5, '1') == strchr(str5, '1'), "5 test failed");
  ck_assert_msg(s21_strchr(str6, '1') == strchr(str6, '1'), "6 test failed");
  ck_assert_msg(s21_strchr(str7, '9') == strchr(str7, '9'), "7 test failed");
  ck_assert_msg(s21_strchr(str7, ' ') == strchr(str7, ' '), "8 test failed");

  // 9 function
}
END_TEST

START_TEST(s21_strcmp_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "999010s",
       str15[1000] = "99901212423154252521552315213512352352423423aaaa",
       str16[100] = " ";
  char str21[100] = "1234", str22[100] = "776asdqe1", str23[100] = "-1213002%s",
       str24[100] = "99901asdass",
       str25[1000] = "99901212423154252521552315213512352352423423aaaa";
  ck_assert_int_eq(s21_strcmp(str11, str21), strcmp(str11, str21));
  ck_assert_int_eq(s21_strcmp(str12, str22), strcmp(str12, str22));
  ck_assert_int_eq(s21_strcmp(str13, str23), strcmp(str13, str23));
  ck_assert_int_eq(s21_strcmp(str14, str24), strcmp(str14, str24));
  ck_assert_int_eq(s21_strcmp(str11, str21), strcmp(str11, str21));
  ck_assert_int_eq(s21_strcmp(str11, str11), strcmp(str11, str11));
  ck_assert_int_eq(s21_strcmp(str15, str25), strcmp(str15, str25));
  ck_assert_int_eq(s21_strcmp(str15, str16), strcmp(str15, str16));

  // 10's function
}
END_TEST

START_TEST(s21_strncmp_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "999010s";
  char str21[100] = "1234", str22[100] = "776asdqe1", str23[100] = "-1213002%s",
       str24[100] = "99901asdass";
  ck_assert_int_eq(s21_strncmp(str11, str21, 5), strncmp(str11, str21, 5));
  ck_assert_int_eq(s21_strncmp(str12, str22, 5), strncmp(str12, str22, 5));
  ck_assert_int_eq(s21_strncmp(str13, str23, 100), strncmp(str13, str23, 50));
  ck_assert_int_eq(s21_strncmp(str14, str24, 5), strncmp(str14, str24, 5));
  ck_assert_int_eq(s21_strncmp(str11, str21, 0), strncmp(str11, str21, 0));

  // 11's function
}
END_TEST

START_TEST(s21_strcpy_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "";
  char str21[100] = "1234", str22[100] = "776asdqe1", str23[100] = "-1213002%s",
       str24[100] = "";
  char str111[100] = "1234", str121[100] = "776832768178",
       str131[100] = "-1213002%s", str141[100] = "";
  char str211[100] = "1234", str221[100] = "776asdqe1", str231[100] = "-1213002%s",
       str241[100] = "";
  ck_assert_str_eq(s21_strcpy(str11, str21), strcpy(str111, str211));
  ck_assert_str_eq(s21_strcpy(str12, str22), strcpy(str121, str221));
  ck_assert_str_eq(s21_strcpy(str13, str23), strcpy(str131, str231));
  ck_assert_str_eq(s21_strcpy(str14, str24), strcpy(str141, str241));
  ck_assert_str_eq(s21_strcpy(str12, str23), strcpy(str121, str231));

  // 12 function
}
END_TEST

START_TEST(s21_strncpy_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "";
  char str21[100] = "1234", str22[100] = "776asdqe1", str23[100] = "-1213002%s",
       str24[100] = "";
  char str111[100] = "1234", str121[100] = "776832768178",
       str131[100] = "-1213002%s", str141[100] = "";
  char str211[100] = "1234", str221[100] = "776asdqe1", str231[100] = "-1213002%s",
       str241[100] = "";
  ck_assert_str_eq(s21_strncpy(str11, str21, 5), strncpy(str111, str211, 5));
  ck_assert_str_eq(s21_strncpy(str12, str22, 7), strncpy(str121, str221, 7));
  ck_assert_str_eq(s21_strncpy(str13, str23, 5), strncpy(str131, str231, 5));
  ck_assert_str_eq(s21_strncpy(str14, str24, 7), strncpy(str141, str241, 7));
  ck_assert_str_eq(s21_strncpy(str12, str23, 5), strncpy(str121, str231, 5));

  // 13's function
}
END_TEST

START_TEST(s21_strcspn_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "";
  char str21[100] = "", str22[100] = "776", str23[100] = "-1213002%s",
       str24[100] = "1234";
  ck_assert_msg(s21_strcspn(str11, str21) == strcspn(str11, str21),
                "1 test failed");
  ck_assert_msg(s21_strcspn(str12, str22) == strcspn(str12, str22),
                "2 test failed");
  ck_assert_msg(s21_strcspn(str13, str23) == strcspn(str13, str23),
                "3 test failed");
  ck_assert_msg(s21_strcspn(str14, str24) == strcspn(str14, str24),
                "4 test failed");
  ck_assert_msg(s21_strcspn(str12, str23) == strcspn(str12, str23),
                "5 test failed");

  // 14's function
}
END_TEST

START_TEST(s21_strerror_test) {
  // ++
  char *str11 = s21_strerror(10);
  char *str21 = strerror(10);
  ck_assert_str_eq(str11, str21);

  char *str12 = s21_strerror(0);
  char *str22 = strerror(0);
  ck_assert_str_eq(str12, str22);

  char *str16 = s21_strerror(-20);
  char *str26 = strerror(-20);
  ck_assert_str_eq(str16, str26);

  char *str13 = s21_strerror(200);
  char *str23 = strerror(200);
  ck_assert_str_eq(str13, str23);

  char *str14 = s21_strerror(30);
  char *str24 = strerror(30);
  ck_assert_str_eq(str14, str24);

  char *str15 = s21_strerror(11);
  char *str25 = strerror(11);
  ck_assert_str_eq(str15, str25);

  // 15 function
}
END_TEST

START_TEST(s21_strlen_test) {
  // ++
  char str1[100] = "1234", str2[100] = "Nice", str3[100] = "00000000",
       str4[100] = "-1-2-3-4-5", str5[100] = "";
  ck_assert_int_eq(s21_strlen(str1), strlen(str1));
  ck_assert_int_eq(s21_strlen(str2), strlen(str2));
  ck_assert_int_eq(s21_strlen(str3), strlen(str3));
  ck_assert_int_eq(s21_strlen(str4), strlen(str4));
  ck_assert_int_eq(s21_strlen(str5), strlen(str5));

  // 16 function
}
END_TEST

START_TEST(s21_strpbrk_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "";
  char str21[100] = "", str22[100] = "776", str23[100] = "-1213002%s",
       str24[100] = "";
  ck_assert_msg(s21_strpbrk(str11, str21) == strpbrk(str11, str21),
                "1 test failed");
  ck_assert_msg(s21_strpbrk(str12, str22) == strpbrk(str12, str22),
                "2 test failed");
  ck_assert_msg(s21_strpbrk(str13, str23) == strpbrk(str13, str23),
                "3 test failed");
  ck_assert_msg(s21_strpbrk(str14, str24) == strpbrk(str14, str24),
                "4 test failed");
  ck_assert_msg(s21_strpbrk(str12, str23) == strpbrk(str12, str23),
                "5 test failed");

  // 17 function
}
END_TEST

START_TEST(s21_strrchr_test) {
  // ++
  char str1[100] = "1234", str2[100] = "Nice", str3[100] = "00000000",
       str4[100] = "-1-2-3-4-5", str5[100] = "";
  ck_assert_msg(s21_strrchr(str1, '0') == strrchr(str1, '0'), "1 test failed");
  ck_assert_msg(s21_strrchr(str2, 'i') == strrchr(str2, 'i'), "2 test failed");
  ck_assert_msg(s21_strrchr(str3, '0') == strrchr(str3, '0'), "3 test failed");
  ck_assert_msg(s21_strrchr(str4, '-') == strrchr(str4, '-'), "4 test failed");
  ck_assert_msg(s21_strrchr(str5, '1') == strrchr(str5, '1'), "5 test failed");

  // 18 function
}
END_TEST

START_TEST(s21_strspn_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "";
  char str21[100] = "", str22[100] = "776", str23[100] = "-1213002%s",
       str24[100] = "1234";
  ck_assert_int_eq(s21_strspn(str11, str21), strspn(str11, str21));
  ck_assert_int_eq(s21_strspn(str12, str22), strspn(str12, str22));
  ck_assert_int_eq(s21_strspn(str13, str23), strspn(str13, str23));
  ck_assert_int_eq(s21_strspn(str14, str24), strspn(str14, str24));
  ck_assert_int_eq(s21_strspn(str12, str23), strspn(str12, str23));

  // 19 function
}
END_TEST

START_TEST(s21_strstr_test) {
  // ++
  char str11[100] = "1234", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "";
  char str21[100] = "", str22[100] = "776", str23[100] = "-1213002%s",
       str24[100] = "1234";
  ck_assert_msg(s21_strstr(str11, str21) == strstr(str11, str21),
                "1 test failed");
  ck_assert_msg(s21_strstr(str12, str22) == strstr(str12, str22),
                "2 test failed");
  ck_assert_msg(s21_strstr(str13, str23) == strstr(str13, str23),
                "3 test failed");
  ck_assert_msg(s21_strstr(str14, str24) == strstr(str14, str24),
                "4 test failed");
  ck_assert_msg(s21_strstr(str12, str23) == strstr(str12, str23),
                "5 test failed");

  // 20 function
}
END_TEST

START_TEST(s21_strtok_test) {
  // ++
  char str11[100] = "1/2/3/4", str12[100] = "776832768178",
       str13[100] = "-1213002%s", str14[100] = "";
  char str21[100] = "/", str22[100] = "", str23[100] = "-1213002%s",
       str24[100] = "1234";
  ck_assert_msg(s21_strtok(str11, str21) == strtok(str11, str21),
                "1 test failed");
  ck_assert_msg(s21_strtok(str12, str22) == strtok(str12, str22),
                "2 test failed");
  ck_assert_msg(s21_strtok(str13, str23) == strtok(str13, str23),
                "3 test failed");
  ck_assert_msg(s21_strtok(str14, str24) == strtok(str14, str24),
                "4 test failed");
  ck_assert_msg(s21_strtok(str12, str23) == strtok(str12, str23),
                "5 test failed");

  // C# 1 function
}
END_TEST



START_TEST(s21_to_lower_test) {
  // ++
  char str11[50] = "Hello_World", str12[50] = "HELLO_WORLD",
       str13[50] = "12ur-u22", str14[50] = "________", str15[50] = "1qaSW_D23";
  ck_assert_str_eq(s21_to_lower(str11), "hello_world");
  ck_assert_str_eq(s21_to_lower(str12), "hello_world");
  ck_assert_str_eq(s21_to_lower(str13), "12ur-u22");
  ck_assert_str_eq(s21_to_lower(str14), "________");
  ck_assert_str_eq(s21_to_lower(str15), "1qasw_d23");

  // C# 3 function
}
END_TEST

START_TEST(s21_insert_test) {
  // ++
  char *str1 = s21_insert("HELLO", "new", 2);
  char *str2 = "HEnewLLO";
  ck_assert_str_eq(str1, str2);
  free(str1);

  char *str3 = s21_insert("nosok", "kot", 3);
  char *str4 = "noskotok";
  ck_assert_str_eq(str3, str4);
  free(str3);

  char *str5 = s21_insert("", "new", 5);
  char *str6 = s21_NULL;
  ck_assert_msg(str5 == str6, "Test 3 insert failed");
  free(str5);

  char *str7 = s21_insert("1", "new", 1);
  char *str8 = "1new";
  ck_assert_str_eq(str7, str8);
  free(str7);

  char *str9 = s21_insert("1", "new", 0);
  char *str10 = "new1";
  ck_assert_str_eq(str9, str10);
  free(str9);

  // C# 4 function
}
END_TEST

START_TEST(s21_trim_test) {
  // ++
  char str11[50] = "_NO_SOK_";
  char str21[50] = "NO_SOK";
  s21_trim(str11, "_");
  ck_assert_str_eq(str11, str21);

  char str12[50] = "";
  char str22[50] = "";
  s21_trim(str21, "+");
  ck_assert_str_eq(str12, str22);

  char str13[50] = "-+_(HE-LLO-+";
  char str23[50] = "HE-LLO";
  s21_trim(str13, "-+_(");
  ck_assert_str_eq(str13, str23);

  char *str14 = "HELLO";
  char *str24 = NULL;
  str14 = s21_trim(str14, "");
  ck_assert_msg(str14 == str24, "1 test failed");
}
END_TEST

START_TEST(s21_Ssprintf_test) {
  char str1[100] = {'\0'};
  char str2[100] = {'\0'};

  sprintf(str1, "%s", "Hello");
  s21_sprintf(str2, "%s", "Hello");
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%.1s", "Hello");
  s21_sprintf(str2, "%.1s", "Hello");
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%7s", "Hello");
  s21_sprintf(str2, "%7s", "Hello");
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%-10s", "Hello");
  s21_sprintf(str2, "%-10s", "Hello");
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);
}
END_TEST

START_TEST(s21_Csprintf_test) {
  char str1[100] = {'\0'};
  char str2[100] = {'\0'};

  sprintf(str1, "%1c %c", 'H', 'z');
  s21_sprintf(str2, "%1c %c", 'H', 'z');
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 50);

  sprintf(str1, "%10c %2c", 'H', 'z');
  s21_sprintf(str2, "%10c %2c", 'H', 'z');
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 50);

  sprintf(str1, "%-1c %-c", 'H', 'z');
  s21_sprintf(str2, "%-1c %-c", 'H', 'z');
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 50);
}
END_TEST

START_TEST(s21_Fsprintf_test) {
  char str1[255] = {'\0'};
  char str2[255] = {'\0'};

  sprintf(str1, "%12.16f %10.17f", 100000000000.14, 100000000000.14);
  s21_sprintf(str2, "%12.16f %10.17f", 100000000000.14, 100000000000.14);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%f", 100000.4);
  s21_sprintf(str2, "%f", 100000.4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%.16f", -100000.4);
  s21_sprintf(str2, "%.16f", -100000.4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%-1f", 100000.4);
  s21_sprintf(str2, "%-1f", 100000.4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%f", -100000.4);
  s21_sprintf(str2, "%f", -100000.4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%+f %+f", -100000.4, 1000.231);
  s21_sprintf(str2, "%+f %+f", -100000.4, 1000.231);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%-20f", 100000.4);
  s21_sprintf(str2, "%-20f", 100000.4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%-+20f", 100000.4);
  s21_sprintf(str2, "%-+20f", 100000.4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%-20f", -100000.4);
  s21_sprintf(str2, "%-20f", -100000.4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%+20f", 100000.4);
  s21_sprintf(str2, "%+20f", 100000.4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%+20f", -100000.4);
  s21_sprintf(str2, "%+20f", -100000.4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  float key = 10000;
  sprintf(str1, "%+20f", key);
  s21_sprintf(str2, "%+20f", key);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  int r2 = sprintf(str2, "%+34.10f%.10i%15.1d%25.10s", 25.3456, 1234, 4567,
                     "HELLOMYDEARFRIEND");
  int r1 = s21_sprintf(str1, "%+34.10f%.10i%15.1d%25.10s", 25.3456, 1234, 4567,
                     "HELLOMYDEARFRIEND");
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);
}
END_TEST

START_TEST(s21_Dsprintf_test) {
  char str1[100] = {'\0'};
  char str2[100] = {'\0'};

  sprintf(str1, "%.d", 4);
  s21_sprintf(str2, "%.d", 4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 30);

  sprintf(str1, "%.10d%%\n", 4);
  s21_sprintf(str2, "%.10d%%\n", 4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 30);

  sprintf(str1, "%d%%\n", -4);
  s21_sprintf(str2, "%d%%\n", -4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 30);

  sprintf(str1, "%-+10d%%\n", 4);
  s21_sprintf(str2, "%-+10d%%\n", 4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 30);

  sprintf(str1, "%-10d%%\n", -4);
  s21_sprintf(str2, "%-10d%%\n", -4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 30);

  sprintf(str1, "%+10d%%\n", 4);
  s21_sprintf(str2, "%+10d%%\n", 4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 30);

  sprintf(str1, "%+10d%%\n", -4);
  s21_sprintf(str2, "%+10d%%\n", -4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 30);

  sprintf(str1, "%+10.5d%%\n", -4);
  s21_sprintf(str2, "%+10.5d%%\n", -4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 30);

  long int var_long = 100;
  sprintf(str1, "%ld%%\n", var_long);
  s21_sprintf(str2, "%ld%%\n", var_long);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 30);

  short var_short = 123;
  sprintf(str1, "%hd%%\n", var_short);
  s21_sprintf(str2, "%hd%%\n", var_short);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 30);

  int r2 = sprintf(str2, "%+-25.3d%25.15d%10.f%15d", 252, 243, 256.34, 15);
  int r1 = s21_sprintf(str1, "%+-25.3d%25.15d%10.f%15d", 252, 243, 256.34, 15);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 150);

  short h = 34;
  r2 = sprintf(str2, "%+10d %+5.1d % 10d % .d %-10ld %-10hd",
  INT_MAX, INT_MIN, 100000000, 100, 1000000000000l, h);
  r1 = s21_sprintf(str1, "%+10d %+5.1d % 10d % .d %-10ld %-10hd",
  INT_MAX, INT_MIN, 100000000, 100, 1000000000000l, h);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);
}
END_TEST

START_TEST(s21_Usprintf_test) {
  char str1[100] = {'\0'};
  char str2[100] = {'\0'};

  sprintf(str1, "%2.5u%%\n", 4);
  s21_sprintf(str2, "%2.5u%%\n", 4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%2.5u%%\n", -4);
  s21_sprintf(str2, "%2.5u%%\n", -4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%10.5u%%\n", 4);
  s21_sprintf(str2, "%10.5u%%\n", 4);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  sprintf(str1, "%-10u%%\n", 421);
  s21_sprintf(str2, "%-10u%%\n", 421);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  short unsigned key_h = 421;
  sprintf(str1, "%-10hu%%\n", key_h);
  s21_sprintf(str2, "%-10hu%%\n", key_h);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);

  long unsigned key_l = 421;
  sprintf(str1, "%-10lu%%\n", key_l);
  s21_sprintf(str2, "%-10lu%%\n", key_l);
  ck_assert_str_eq(str1, str2);
  makefreeArr(str1, str2, 100);
  char c[255] = {'\0'}, d[255] = {'\0'};
  s21_sprintf(c, "%10.s %10ls %-10ls %-3ls %.ls %.3ls %.10ls", "hello",
                L"hello", L"hello", L"hello", L"hello", L"hello", L"hello");
  sprintf(d, "%10.s %10ls %-10ls %-3ls %.ls %.3ls %.10ls", "hello", L"hello",
            L"hello", L"hello", L"hello", L"hello", L"hello");
  ck_assert_str_eq(c, d);
  makefreeArr(c, d, 100);
}
END_TEST

START_TEST(s21_Complexsprintf_test) {
  char str1[255] = {'\0'};
  char str2[255] = {'\0'};
  short h1 = 0;
  int r2 = sprintf(str2, "%+f %+d %+hd %+ld %+i", 0.0f, 0, h1, 0l, 0);
  int r1 = s21_sprintf(str1, "%+f %+d %+hd %+ld %+i", 0.0f, 0, h1, 0l, 0);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 150);

  r2 = sprintf(str2, "|%10.5i|%10.5i|%+20li|% 20li|% 10hi|%9.7hi|%10.i|%10.10i|% i|",
                INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, SHRT_MAX, SHRT_MIN, 0, 12345, -12345);
  r1 = s21_sprintf(str1, "|%10.5i|%10.5i|%+20li|% 20li|% 10hi|%9.7hi|%10.i|%10.10i|% i|",
                INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, SHRT_MAX, SHRT_MIN, 0, 12345, -12345);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);

  wchar_t c1 = 'T', c2 = 'Z';
  r2 = sprintf(str2, "%10c%-10c%25c%-30c%25c%c%2c%c%lc%-40lc", 'a', 'e',
                     'f', 'R', 'Q', 'P', 'L', 'x', c1, c2);
  r1 = s21_sprintf(str1, "%10c%-10c%25c%-30c%25c%c%2c%c%lc%-40lc", 'a', 'e',
                     'f', 'R', 'Q', 'P', 'L', 'x', c1, c2);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);

  r2 = sprintf(str2, "%+-10.3f%+10.2f% 15.f%+.6f%.10f%-10.f%5.20f%25.f%+10.f%.f",
        2546.4324, 3452.4325, 5678.43256, 456789.243242,
        3456789123.43245, 12345.6788, 34.4325432, 4325678.43242,
        34567.2345432, 34567.43244);
  r1 = s21_sprintf(str1, "%+-10.3f%+10.2f% 15.f%+.6f%.10f%-10.f%5.20f%25.f%+10.f%.f",
        2546.4324, 3452.4325, 5678.43256, 456789.243242,
        3456789123.43245, 12345.6788, 34.4325432, 4325678.43242,
        34567.2345432, 34567.43244);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);

  short unsigned z = UINT16_MAX;
  long unsigned l = UINT64_MAX;
  r2 = sprintf(str2, "|%u|%15u|%-20u|%10u|%-15.10u|%20.5u|%.u|%.10u|%-20.12lu|%19hu|",
                      54321u, 123456789u, -4, 65017u, UINT_MAX, 0u, 27468u, 1000000u, l, z);
  r1 = s21_sprintf(str1, "|%u|%15u|%-20u|%10u|%-15.10u|%20.5u|%.u|%.10u|%-20.12lu|%19hu|",
                      54321u, 123456789u, -4, 65017u, UINT_MAX, 0u, 27468u, 1000000u, l, z);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);

  wchar_t s[10] = {'h', 'e', 'l', 'l', 'o'};
  r2 = sprintf(str2, "|%s|%23s|%-15s|%10.s|%15.2s|%4.1s|%10s|%15ls|%15.3ls|%10.4s|",
                     "aboba", "helloworld", "ABOBA", "ABOBBAAA", "AAABOBA",
                     "QWERTY", "ABOBAAAAA", s, s, "AAAAABOOOOOBAAA");
  r1 = s21_sprintf(str1, "|%s|%23s|%-15s|%10.s|%15.2s|%4.1s|%10s|%15ls|%15.3ls|%10.4s|",
                     "aboba", "helloworld", "ABOBA", "ABOBBAAA", "AAABOBA",
                     "QWERTY", "ABOBAAAAA", s, s, "AAAAABOOOOOBAAA");
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);

  r2 = sprintf(str2, "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%");
  r1 = s21_sprintf(str1, "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%");
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);

  l = UINT64_MAX;
  r2 = sprintf(str2, "|%hi|%hi|  |%li|%li| |%i|%i|\n|%hd|%hd|  |%ld|%ld|  |%d|%d|\n|%hu|%u|%lu|",
              SHRT_MAX, SHRT_MIN, LONG_MAX, LONG_MIN, INT_MAX, INT_MIN,
              SHRT_MAX, SHRT_MIN, LONG_MAX, LONG_MIN, INT_MAX, INT_MIN,
              UINT16_MAX, UINT16_MAX, l);
  r1 = s21_sprintf(str1, "|%hi|%hi|  |%li|%li| |%i|%i|\n|%hd|%hd|  |%ld|%ld|  |%d|%d|\n|%hu|%u|%lu|",
              SHRT_MAX, SHRT_MIN, LONG_MAX, LONG_MIN, INT_MAX, INT_MIN,
              SHRT_MAX, SHRT_MIN, LONG_MAX, LONG_MIN, INT_MAX, INT_MIN,
              UINT16_MAX, UINT16_MAX, l);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);

  r2 = sprintf(str2, "qwertyuiop[]\';lkjhgfdd623045786056azxscvbnm,./");
  r1 = s21_sprintf(str1, "qwertyuiop[]\';lkjhgfdd623045786056azxscvbnm,./");
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);

  r2 = sprintf(str2, "%f %f", 1.0/0.0, -1.0/0.0);
  r1 = s21_sprintf(str1, "%f %f", 1.0/0.0, -1.0/0.0);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);

  double d1 = 9199999999999999999.0;
  r2 = sprintf(str2, "|%.10f|%.f|  |%.f|% .2f|  |%10.5d|%10.1d|  |%10.5i|%10.1i|",
                      d1, d1, 1.0/0.0, -1.0/0.0, 34, 34, 34, 34);
  r1 = s21_sprintf(str1, "|%.10f|%.f|  |%.f|% .2f|  |%10.5d|%10.1d|  |%10.5i|%10.1i|",
                      d1, d1, 1.0/0.0, -1.0/0.0, 34, 34, 34, 34);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r2, r1);
  makefreeArr(str1, str2, 255);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_memchr_test);
  tcase_add_test(tc1_1, s21_memcmp_test);
  tcase_add_test(tc1_1, s21_memcpy_test);
  tcase_add_test(tc1_1, s21_memmove_test);
  tcase_add_test(tc1_1, s21_memset_test);
  tcase_add_test(tc1_1, s21_strcat_test);
  tcase_add_test(tc1_1, s21_strncat_test);
  tcase_add_test(tc1_1, s21_strchr_test);
  tcase_add_test(tc1_1, s21_strcmp_test);
  tcase_add_test(tc1_1, s21_strncmp_test);
  tcase_add_test(tc1_1, s21_strcpy_test);
  tcase_add_test(tc1_1, s21_strncpy_test);
  tcase_add_test(tc1_1, s21_strcspn_test);
  tcase_add_test(tc1_1, s21_strerror_test);
  tcase_add_test(tc1_1, s21_strlen_test);
  tcase_add_test(tc1_1, s21_strpbrk_test);
  tcase_add_test(tc1_1, s21_strrchr_test);
  tcase_add_test(tc1_1, s21_strspn_test);
  tcase_add_test(tc1_1, s21_strstr_test);
  tcase_add_test(tc1_1, s21_strtok_test);
  tcase_add_test(tc1_1, s21_to_lower_test);
  tcase_add_test(tc1_1, s21_insert_test);
  tcase_add_test(tc1_1, s21_trim_test);
  tcase_add_test(tc1_1, s21_Ssprintf_test);
  tcase_add_test(tc1_1, s21_Csprintf_test);
  tcase_add_test(tc1_1, s21_Fsprintf_test);
  tcase_add_test(tc1_1, s21_Dsprintf_test);
  tcase_add_test(tc1_1, s21_Usprintf_test);
  tcase_add_test(tc1_1, s21_Complexsprintf_test);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}

